'use client';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import type { EvaluationResult } from '@/lib/types';
import { cn } from '@/lib/utils';
import { CheckCircle, AlertTriangle, XCircle, FileText, Sparkles, Leaf } from 'lucide-react';

type SustainabilityReportProps = {
  report: EvaluationResult;
};

const ratingConfig = {
  Sustainable: {
    color: 'text-primary',
    bgColor: 'bg-primary/10',
    borderColor: 'border-primary/20',
    Icon: CheckCircle,
    progressColor: 'bg-primary',
  },
  Moderate: {
    color: 'text-[hsl(var(--chart-4))]',
    bgColor: 'bg-[hsl(var(--chart-4))]/10',
    borderColor: 'border-[hsl(var(--chart-4))]/20',
    Icon: AlertTriangle,
    progressColor: 'bg-[hsl(var(--chart-4))]',
  },
  Unsustainable: {
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
    borderColor: 'border-destructive/20',
    Icon: XCircle,
    progressColor: 'bg-destructive',
  },
};

export function SustainabilityReport({ report }: SustainabilityReportProps) {
  const config = ratingConfig[report.rating];

  return (
    <Card className={cn('transition-all duration-500 ease-in-out transform animate-in fade-in', config.bgColor, config.borderColor)}>
      <CardHeader>
        <div className="flex justify-between items-start">
          <div>
            <CardTitle className="font-headline text-3xl flex items-center gap-2">
              <config.Icon className={cn('h-8 w-8', config.color)} />
              Sustainability Analysis
            </CardTitle>
            <CardDescription className="text-lg mt-1">
              Overall Rating: <Badge variant="outline" className={cn('text-lg font-bold', config.color, config.bgColor, config.borderColor)}>{report.rating}</Badge>
            </CardDescription>
          </div>
          <div className="text-right">
             <p className="text-sm text-muted-foreground">Sustainability Score</p>
             <p className={cn('font-bold text-4xl', config.color)}>{report.sustainability_score}</p>
          </div>
        </div>
        <div className="pt-4">
          <Progress value={report.sustainability_score} indicatorClassName={config.progressColor} />
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <h3 className="text-lg font-semibold mb-2 flex items-center gap-2 font-headline">
            <Sparkles className="h-5 w-5 text-primary" /> Key Factors
          </h3>
          <ul className="list-disc list-inside space-y-1 text-muted-foreground">
            {report.key_factors.map((factor, index) => <li key={index}>{factor}</li>)}
          </ul>
        </div>
        <Separator />
         <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2 font-headline">
            <Sparkles className="h-5 w-5 text-primary" /> AI Recommendations for Improvement
          </h3>
          <div className="space-y-3">
            {report.recommendations.map((rec, index) => (
              <div key={index} className="flex items-start gap-3 p-3 bg-background/50 rounded-lg">
                <Leaf className="h-5 w-5 text-primary mt-1 shrink-0" />
                <p className="text-muted-foreground">{rec}</p>
              </div>
            ))}
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Dialog>
          <DialogTrigger asChild>
            <Button variant="outline" className="w-full">
              <FileText className="mr-2 h-4 w-4" />
              View Detailed Report
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-3xl h-[80vh] flex flex-col">
            <DialogHeader>
              <DialogTitle className="font-headline text-2xl">Detailed Sustainability Report</DialogTitle>
              <DialogDescription>
                A comprehensive analysis generated by AI.
              </DialogDescription>
            </DialogHeader>
            <div className="overflow-y-auto p-1 flex-grow pr-4">
              <pre className="text-sm whitespace-pre-wrap font-body text-muted-foreground">
                  {report.detailed_report}
              </pre>
            </div>
          </DialogContent>
        </Dialog>
      </CardFooter>
    </Card>
  );
}
